package com.example.heng.jredu.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "classProj".
 */
public class ClassProj {

    private Long id;
    private String projId;
    private String rgdtDate;
    private String endDate;
    private String remark;
    private String photoUri;
    private String vedioCt;

    public ClassProj() {
    }

    public ClassProj(Long id) {
        this.id = id;
    }

    public ClassProj(Long id, String projId, String rgdtDate, String endDate, String remark, String photoUri, String vedioCt) {
        this.id = id;
        this.projId = projId;
        this.rgdtDate = rgdtDate;
        this.endDate = endDate;
        this.remark = remark;
        this.photoUri = photoUri;
        this.vedioCt = vedioCt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProjId() {
        return projId;
    }

    public void setProjId(String projId) {
        this.projId = projId;
    }

    public String getRgdtDate() {
        return rgdtDate;
    }

    public void setRgdtDate(String rgdtDate) {
        this.rgdtDate = rgdtDate;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getPhotoUri() {
        return photoUri;
    }

    public void setPhotoUri(String photoUri) {
        this.photoUri = photoUri;
    }

    public String getVedioCt() {
        return vedioCt;
    }

    public void setVedioCt(String vedioCt) {
        this.vedioCt = vedioCt;
    }

}
